version: "3.8"

services:
  app:
    build: .
    container_name: nexora_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
      - redis 
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - PG_HOST=${PGL_HOST}
      - PG_USER=${PGL_USER}
      - PG_PASSWORD=${PGL_PASSWORD}
      - PG_DATABASE=${PGL_DATABASE}
      - PG_PORT=${PGL_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_URL=${REDIS_URL}
      - REDIS_TOKEN=${REDIS_TOKEN}

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "${PGL_PORT}:${PGL_PORT}"
    environment:
      POSTGRES_USER: ${PGL_USER}
      POSTGRES_PASSWORD: ${PGL_PASSWORD}
      POSTGRES_DB: ${PGL_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

volumes:
  pgdata:
